export const MOCK = [
  {
    id: 1,
    departureCity: "Lillehammer",
    arriveCity: "Kotaagung",
    departureDate: "2021-01-21T09:49:32Z",
    flightDurationMinutes: 195,
    flightCompany: "Bauch LLC",
    flightCompanyLogo: null,
    price: 3990.3,
    priceCurrency: null,
  },
  {
    id: 2,
    departureCity: "Karangarjo",
    arriveCity: "Midoun",
    departureDate: "2021-08-25T16:30:24Z",
    flightDurationMinutes: 78,
    flightCompany: "Pfeffer LLC",
    flightCompanyLogo: null,
    price: 2069.9,
    priceCurrency: null,
  },
  {
    id: 3,
    departureCity: "Kanungu",
    arriveCity: "Sihanoukville",
    departureDate: "2022-04-17T15:20:11Z",
    flightDurationMinutes: 73,
    flightCompany: "Padberg and Sons",
    flightCompanyLogo: "http://dummyimage.com/470x476.png/dddddd/000000",
    price: 122.7,
    priceCurrency: null,
  },
  {
    id: 4,
    departureCity: "Chongmin",
    arriveCity: "Pampas",
    departureDate: "2022-03-18T03:58:02Z",
    flightDurationMinutes: 260,
    flightCompany: "Altenwerth, Hilpert and Terry",
    flightCompanyLogo: null,
    price: 2122.7,
    priceCurrency: null,
  },
  {
    id: 5,
    departureCity: "Manicaragua",
    arriveCity: "Villa Ascasubi",
    departureDate: "2021-09-13T15:24:05Z",
    flightDurationMinutes: 54,
    flightCompany: "Emmerich Group",
    flightCompanyLogo: null,
    price: 882.8,
    priceCurrency: null,
  },
]
